# Generated by Django 5.2.7 on 2026-02-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002 weight based shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='price_eur',
        ),
    ]
