# Generated by Django 5.2.7 on 2025-12-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('translator', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, help_text='13-digit ISBN.', max_length=13, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('stock', models.IntegerField(default=0, help_text='Current number of units in stock.')),
                ('year', models.CharField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=4, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Book cover image.', null=True, upload_to='book_covers/')),
                ('book_size', models.CharField(choices=[('JIBI_SHOMIZ', 'جیبی (شومیز)'), ('JIBI_GHALINGOR', 'جیبی (گالینگور)'), ('PALTUI_SHOMIZ', 'پالتویی (شومیز)'), ('PALTUI_GHALINGOR', 'پالتویی (گالینگور)'), ('RAGHEI_SHOMIZ', 'رقعی (شومیز)'), ('RAGHEI_GHALINGOR', 'رقعی (گالینگور)'), ('VAZIRI_SHOMIZ', 'وزیری (شومیز)'), ('VAZIRI_GHALINGOR', 'وزیری (گالینگور)'), ('RAHLI_SHOMIZ', 'رحلی (شومیز)'), ('RAHLI_GHALINGOR', 'رحلی (گالینگور)'), ('KHESHTI_SHOMIZ', 'خشتی (شومیز)'), ('KHESHTI_GHALINGOR', 'خشتی (گالینگور)')], default='JIBI_SHOMIZ', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Designates if the book is available for purchase.')),
                ('sold_count', models.IntegerField(default=0, help_text='Cached total units sold for this book.')),
                ('genres', models.ManyToManyField(blank=True, related_name='books', to='shop.genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='The final total price of the order.', max_digits=10)),
                ('user', models.ForeignKey(help_text='The user who placed the order (null if guest or user deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('books', models.ManyToManyField(blank=True, related_name='recommended_groups', to='shop.book')),
            ],
            options={
                'verbose_name': 'Recommended Book Group',
                'verbose_name_plural': 'Recommended Book Groups',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title_snapshot', models.CharField(editable=False, max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=0, help_text='The price of the book at the exact time of purchase.', max_digits=9)),
                ('book', models.ForeignKey(help_text='The book purchased. Set to null if the book is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('order', 'book')},
            },
        ),
    ]
