# Generated by Django 5.2.7 on 2025-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_size',
            field=models.CharField(choices=[('A5', 'A5 (148 × 210 mm)'), ('B5', 'B5 (176 × 250 mm)'), ('A4', 'A4 (210 × 297 mm)'), ('POCKET', 'Pocket'), ('CUSTOM', 'Custom')], default='B5', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
