# Generated by Django 5.2.7 on 2025-12-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_book_book_size_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
