# Generated by Django 5.2.7 on 2025-12-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_date_book_published_date_book_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
