# Generated by Django 5.2.7 on 2025-12-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Legacy field (unused). Optional for admin panel compatibility.', max_length=150, null=True, unique=True),
        ),
    ]
